language: php

sudo: false

php:
  - 7.2

# Environment Variables to set
env:
  global:
    # Contains a $GITHUB_TOKEN env var for use with composer to avoid API limits.
    - secure: "JPIIdecDmF2AsgH3b5QWYzr2TunB4tpIBl0/64EGsWZ+5A85Co3NN+eSshgWI5vOjaaJji/S2rKwMRvV9h/YceTL/UH5D2xd/HobRpHAaJSyjp5cplQawokzR/+PrikjmbwTZdeiIaHpUMCqbQvV2+Jq+Vx5vD28+hya1yTdQsk="

# Cache the composer directories, only allowed if using the container based setup
# which depends on setting sudo to false
cache:
  directories:
    - $HOME/.composer/cache

# Branches to be built or not
branches:
  # Blacklist these branches
  except:
    - gh-pages

before_install:
  - composer self-update
  - mkdir -p build/logs

install:
  - composer install --dev --no-interaction

before_script:
  - phpenv rehash
  - vendor/bin/phpcs --config-set installed_paths vendor/loadsys/loadsys_codesniffer,vendor/cakephp/cakephp-codesniffer

script:
  - vendor/bin/phpcs -np --extensions=php --standard=Loadsys ./src ./tests
  - vendor/bin/phpunit --coverage-clover=build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v

notifications:
  email: false
