language: php

sudo: false

php:
  - 5.6

# Environment Variables to set
env:
  global:
    # Contains a $GITHUB_TOKEN env var for use with composer to avoid API limits.
    - secure: "JPIIdecDmF2AsgH3b5QWYzr2TunB4tpIBl0/64EGsWZ+5A85Co3NN+eSshgWI5vOjaaJji/S2rKwMRvV9h/YceTL/UH5D2xd/HobRpHAaJSyjp5cplQawokzR/+PrikjmbwTZdeiIaHpUMCqbQvV2+Jq+Vx5vD28+hya1yTdQsk="


# Cache the composer directories, only allowed if using the container based setup
# which depends on setting sudo to false
cache:
  directories:
    - $HOME/.composer/cache

# Branches to be built or not
branches:
  # Blacklist these branches
  except:
    - gh-pages

before_install:
  - composer self-update

install:
  - composer config -g github-oauth.github.com $GITHUB_TOKEN
  - composer install --no-interaction

before_script:
  - phpenv rehash
  - vendor/bin/phpcs --config-set installed_paths vendor/loadsys/loadsys_codesniffer,vendor/cakephp/cakephp-codesniffer

script:
  - vendor/bin/phpcs -p --extensions=php --standard=Loadsys src tests
  - vendor/bin/phpunit --coverage-xml=build/logs/clover.xml
  - php vendor/bin/coveralls -v

notifications:
  email: false
